---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redirect
  labels:
    app: redirect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redirect
  template:
    metadata:
      labels:
        app: redirect
    spec:
      containers:
      - name: redirect
        image: redirect:latest
        envFrom:
        - configMapRef:
            name: redirect-env
